#pragma once

#include "CoreMinimal.h"
#include "WYAQuestTypes.generated.h"

/**
 * Which pipeline owns this quest.
 * Main story quests are static/hand-authored.
 * Side quests are AI-generated by UWYAAISubsystem.
 * These two types must never be mixed at assignment — see decisions-log.md.
 */
UENUM(BlueprintType)
enum class EWYAQuestType : uint8
{
	MainStory  UMETA(DisplayName = "Main Story"),
	SideQuest  UMETA(DisplayName = "Side Quest"),
};

/** A quest handed to the player. Intentionally flat — quest logic lives in the quest manager. */
USTRUCT(BlueprintType)
struct FWYAQuest
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly)
	FString ID;

	UPROPERTY(BlueprintReadOnly)
	EWYAQuestType Type = EWYAQuestType::SideQuest;

	UPROPERTY(BlueprintReadOnly)
	FString Title;

	UPROPERTY(BlueprintReadOnly)
	FString Body;

	bool IsValid() const { return !ID.IsEmpty(); }
};
