#pragma once

#include "CoreMinimal.h"
#include "Location/WYAGeoTypes.h"
#include "WYAContractTypes.generated.h"

/**
 * Contract payout tier — drives Gold reward range and implied difficulty.
 *
 *   Standard   — street-level, 10–20 Gold. Posted by local factions.
 *   Priority   — named target with history, 20–35 Gold. Faction-sanctioned.
 *   HighTable  — sanctioned elimination, 35–50 Gold. High Table mediated.
 */
UENUM(BlueprintType)
enum class EWYAContractTier : uint8
{
    Standard   UMETA(DisplayName = "Standard"),
    Priority   UMETA(DisplayName = "Priority"),
    HighTable  UMETA(DisplayName = "High Table"),
};

/**
 * A contract posted on the board — eliminate a named target for Gold.
 *
 * Generated by WYAAISubsystem against the player's GPS location.
 * Managed by WYAContractSubsystem (board + active tracking + payout).
 */
USTRUCT(BlueprintType)
struct FWYAContract
{
    GENERATED_BODY()

    /** Unique ID — "contract_<timestamp_ticks>" */
    UPROPERTY(BlueprintReadOnly)
    FString ID;

    /** Full name or alias, e.g. "Victor Hale" or "The Sutton Broker" */
    UPROPERTY(BlueprintReadOnly)
    FString TargetName;

    /** One-line description, e.g. "Scavenger enforcer, South Ward" */
    UPROPERTY(BlueprintReadOnly)
    FString TargetRole;

    /** Human-readable last-seen location, derived from GPS context */
    UPROPERTY(BlueprintReadOnly)
    FString LastSeen;

    /** 2-3 sentence backstory — reason for the contract */
    UPROPERTY(BlueprintReadOnly)
    FString Intel;

    /** Gold reward on completion */
    UPROPERTY(BlueprintReadOnly)
    int32 GoldReward = 10;

    UPROPERTY(BlueprintReadOnly)
    EWYAContractTier Tier = EWYAContractTier::Standard;

    /** GPS coord the contract was generated for */
    UPROPERTY(BlueprintReadOnly)
    FWYAGeoCoord GeneratedForCoord;

    bool IsValid() const { return !ID.IsEmpty() && !TargetName.IsEmpty(); }
};

/** In-flight or ready contract waiting in the pre-gen buffer */
USTRUCT()
struct FWYAPregeneratedContract
{
    GENERATED_BODY()

    FWYAContract Contract;
    bool bReady = false;
};

/**
 * Live tracking state for a contract in progress.
 * Created when TakeContract() fires, consumed on CompleteContract().
 */
USTRUCT()
struct FWYAContractRunState
{
    GENERATED_BODY()

    FString ContractID;

    /** World time when TakeContract() was called. */
    float StartTimeSecs = 0.f;

    /** How many security NPCs reached EWYAAlertState::Alerted during this run. */
    int32 AlertCount = 0;

    /** True if the player took any damage during this run. */
    bool bTookDamage = false;

    /** True once the player has reached the exfil point. */
    bool bExfilReached = false;

    bool IsValid() const { return !ContractID.IsEmpty(); }
};
