#pragma once

#include "CoreMinimal.h"
#include "Location/WYAGeoTypes.h"
#include "WYAContractTypes.generated.h"

/**
 * Which phase of a contract run carries the most load.
 * Derived at generation time from Tier (and eventually SecurityType/LocationType).
 * Passed to the assistant on contract taken. Burke tracks patterns over time.
 *
 *   Phase1Heavy — approach is the problem (heavy security, indoor, hard to reach)
 *   Phase2Heavy — the hit runs long (tough target, guards, retreat mechanic prominent)
 *   Phase3Heavy — extraction is contested (fast response, many security, exit is hot)
 *   Compound    — all three phases are loaded (HighTable tier)
 */
UENUM(BlueprintType)
enum class EWYAPhaseWeight : uint8
{
    Phase1Heavy  UMETA(DisplayName = "Phase 1 Heavy — Approach"),
    Phase2Heavy  UMETA(DisplayName = "Phase 2 Heavy — Hit"),
    Phase3Heavy  UMETA(DisplayName = "Phase 3 Heavy — Extraction"),
    Compound     UMETA(DisplayName = "Compound — All Phases"),
};

/**
 * Contract payout tier — drives Gold reward range and implied difficulty.
 *
 *   Standard   — street-level, 10–20 Gold. Posted by local factions.
 *   Priority   — named target with history, 20–35 Gold. Faction-sanctioned.
 *   HighTable  — sanctioned elimination, 35–50 Gold. High Table mediated.
 */
UENUM(BlueprintType)
enum class EWYAContractTier : uint8
{
    Standard   UMETA(DisplayName = "Standard"),
    Priority   UMETA(DisplayName = "Priority"),
    HighTable  UMETA(DisplayName = "High Table"),
};

/**
 * A contract posted on the board — eliminate a named target for Gold.
 *
 * Generated by WYAAISubsystem against the player's GPS location.
 * Managed by WYAContractSubsystem (board + active tracking + payout).
 */
USTRUCT(BlueprintType)
struct FWYAContract
{
    GENERATED_BODY()

    /** Unique ID — "contract_<timestamp_ticks>" */
    UPROPERTY(BlueprintReadOnly)
    FString ID;

    /** Full name or alias, e.g. "Victor Hale" or "The Sutton Broker" */
    UPROPERTY(BlueprintReadOnly)
    FString TargetName;

    /** One-line description, e.g. "Scavenger enforcer, South Ward" */
    UPROPERTY(BlueprintReadOnly)
    FString TargetRole;

    /** Human-readable last-seen location, derived from GPS context */
    UPROPERTY(BlueprintReadOnly)
    FString LastSeen;

    /** 2-3 sentence backstory — reason for the contract */
    UPROPERTY(BlueprintReadOnly)
    FString Intel;

    /** Gold reward on completion */
    UPROPERTY(BlueprintReadOnly)
    int32 GoldReward = 10;

    UPROPERTY(BlueprintReadOnly)
    EWYAContractTier Tier = EWYAContractTier::Standard;

    /**
     * Phase load profile — derived at generation time from Tier.
     * Passed to the assistant on contract taken so it can frame the briefing.
     * Tracked by WYAContractSubsystem for Burke pattern detection.
     */
    UPROPERTY(BlueprintReadOnly)
    EWYAPhaseWeight PhaseWeight = EWYAPhaseWeight::Phase2Heavy;

    /** GPS coord the contract was generated for */
    UPROPERTY(BlueprintReadOnly)
    FWYAGeoCoord GeneratedForCoord;

    bool IsValid() const { return !ID.IsEmpty() && !TargetName.IsEmpty(); }

    /** Derive PhaseWeight from Tier — used at parse time and on load. */
    static EWYAPhaseWeight DerivePhaseWeight(EWYAContractTier InTier)
    {
        switch (InTier)
        {
        case EWYAContractTier::HighTable: return EWYAPhaseWeight::Compound;
        case EWYAContractTier::Priority:  return EWYAPhaseWeight::Phase3Heavy;
        default:                          return EWYAPhaseWeight::Phase2Heavy;
        }
    }
};

/** In-flight or ready contract waiting in the pre-gen buffer */
USTRUCT()
struct FWYAPregeneratedContract
{
    GENERATED_BODY()

    FWYAContract Contract;
    bool bReady = false;
};

/**
 * Live tracking state for a contract in progress.
 * Created when TakeContract() fires, consumed on CompleteContract().
 */
USTRUCT()
struct FWYAContractRunState
{
    GENERATED_BODY()

    FString ContractID;

    /** World time when TakeContract() was called. */
    float StartTimeSecs = 0.f;

    /**
     * How many security NPCs reached EWYAAlertState::Alerted during this run.
     * Tracked for stats and phase-weight analysis — does NOT void Ghost.
     */
    int32 AlertCount = 0;

    /**
     * True once a living security NPC walks within discovery range of the
     * downed target's body. This is what voids the Ghost bonus.
     * An alerted guard does NOT void Ghost — leaving before body discovery does.
     */
    bool bBodyDiscovered = false;

    /** True if the player took any damage during this run. */
    bool bTookDamage = false;

    /** True once the player has reached the exfil point. */
    bool bExfilReached = false;

    bool IsValid() const { return !ContractID.IsEmpty(); }
};
