[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Script/WhereYouAre.WYAGameMode
GlobalDefaultServerGameMode=/Script/WhereYouAre.WYAGameMode
GlobalDefaultGameState=/Script/WhereYouAre.WYAGameState

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/WhereYouAre")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/WhereYouAre")

[/Script/Engine.RendererSettings]
; Vulkan-first on Linux, DX12 on Windows
r.DefaultFeature.AntiAliasing=4
; FSR settings (AMD hardware - no DLSS)
r.FidelityFX.FSR3.Enabled=1
r.FidelityFX.FSR3.QualityMode=2

[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsNotConsideredByGC=1048576
gc.SizeOfPermanentObjectPool=0

[/Script/OnlineSubsystemUtils.IpNetDriver]
MaxClientRate=15000
MaxInternetClientRate=10000

[URL]
GameName=WhereYouAre
